### ISSUE TITLE
Prestart.js can't be loaded, possibly causing the mod to not work in 1.2.1 ver

### ISSUE THREAD

**Issue by lubkuluk** [EL20202/crosscode-font-utils#1]
The 1.0.0 version was working just fine. The colors up to orange also work but anything beyond that doesn't

**Comment by elluminance** [comment]
I'm afraid I cannot reproduce the bug - I tried a fresh install of CCLoader with only the mod, and it was able to load the game just fine.

Did you download the mod by downloading the ZIP, or via the `font-utils.ccmod` bundled with the release?
Support will not be provided unless it is the latter, as the downloaded ZIP simply will not work by default.
